import chalk from 'chalk';

interface GuideOptions {
  agent?: string;
}

const AGENT_GUIDES: Record<string, { title: string; setup: string[]; workflow: string[] }> = {
  'claude-code': {
    title: 'Claude Code',
    setup: [
      'Install Claude Code: https://docs.anthropic.com/claude-code',
      'Ensure your project has a CLAUDE.md file (auto-generated by scaffold)',
      'Open your project directory in the terminal',
    ],
    workflow: [
      'claude  — Start a Claude Code session in your project',
      'Claude reads CLAUDE.md automatically for project context',
      '',
      'Example prompts:',
      '  "Add a users CRUD module with Prisma model"',
      '  "Create a React component for user profile with Tailwind"',
      '  "Write unit tests for the auth service"',
      '  "Refactor the health controller to include DB status"',
      '',
      'Best practices:',
      '  • Keep CLAUDE.md up-to-date with conventions',
      '  • Use /compact to reduce context when sessions grow large',
      '  • Ask Claude to run tests after making changes',
    ],
  },
  'copilot-cli': {
    title: 'GitHub Copilot CLI',
    setup: [
      'Install GitHub CLI: https://cli.github.com',
      'Install Copilot extension: gh extension install github/gh-copilot',
      'Authenticate: gh auth login',
      'Ensure .github/copilot-instructions.md exists (auto-generated by scaffold)',
    ],
    workflow: [
      'gh copilot suggest "..."  — Get command suggestions',
      'gh copilot explain "..."  — Explain a command',
      '',
      'In VS Code with Copilot Chat:',
      '  @workspace — Ask questions about the entire project',
      '  Copilot reads .github/copilot-instructions.md for context',
      '',
      'Example prompts:',
      '  @workspace "How do I add a new module?"',
      '  @workspace "Generate a service for order management"',
      '  "Explain this NestJS guard"',
      '',
      'Best practices:',
      '  • Keep copilot-instructions.md current with project rules',
      '  • Use @workspace for project-aware suggestions',
      '  • Reference specific files with #file for targeted help',
    ],
  },
};

export async function guideCommand(options: GuideOptions): Promise<void> {
  console.log(chalk.blue('\n🤖 AI Agent Workflow Guide\n'));

  if (options.agent && AGENT_GUIDES[options.agent]) {
    printAgentGuide(options.agent);
    return;
  }

  // Show overview
  console.log(chalk.white('  Agent Harness generates AI-ready projects with:\n'));
  console.log(chalk.gray('    📄 CLAUDE.md                      — Instructions for Claude Code'));
  console.log(chalk.gray('    📄 .github/copilot-instructions.md — Instructions for GitHub Copilot'));
  console.log('');

  console.log(chalk.white('  Supported AI agents:\n'));
  for (const [key, guide] of Object.entries(AGENT_GUIDES)) {
    console.log(chalk.cyan(`    ${guide.title}`), chalk.gray(`(agent-harness guide --agent ${key})`));
  }

  console.log(chalk.white('\n  Recommended workflow:\n'));
  console.log(chalk.gray('    1. Generate your project scaffold'));
  console.log(chalk.cyan('       $ agent-harness scaffold -t react -n frontend'));
  console.log(chalk.cyan('       $ agent-harness scaffold -t nestjs -n backend'));
  console.log('');
  console.log(chalk.gray('    2. Open in your AI coding tool'));
  console.log(chalk.cyan('       $ cd frontend && claude'));
  console.log(chalk.gray('       or open in VS Code with Copilot'));
  console.log('');
  console.log(chalk.gray('    3. The AI agent reads CLAUDE.md / copilot-instructions.md'));
  console.log(chalk.gray('       and understands your project structure, conventions, and stack'));
  console.log('');
  console.log(chalk.gray('    4. Ask the AI to build features iteratively'));
  console.log(chalk.cyan('       "Add a user registration form with validation"'));
  console.log(chalk.cyan('       "Create a REST endpoint for product catalog"'));
  console.log('');

  console.log(chalk.white('  Full guide for a specific agent:\n'));
  console.log(chalk.cyan('    $ agent-harness guide --agent claude-code'));
  console.log(chalk.cyan('    $ agent-harness guide --agent copilot-cli'));
  console.log('');
}

function printAgentGuide(agentKey: string) {
  const guide = AGENT_GUIDES[agentKey];

  console.log(chalk.white(`  📖 ${guide.title} Workflow\n`));

  console.log(chalk.white('  Setup:'));
  for (const step of guide.setup) {
    console.log(chalk.gray(`    • ${step}`));
  }
  console.log('');

  console.log(chalk.white('  Workflow:'));
  for (const line of guide.workflow) {
    if (line === '') {
      console.log('');
    } else if (line.startsWith('  ')) {
      console.log(chalk.cyan(`    ${line}`));
    } else {
      console.log(chalk.gray(`    ${line}`));
    }
  }
  console.log('');
}
